name: Go
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Test
      run: |
        go get github.com/golangci/golangci-lint/cmd/golangci-lint
        $GOPATH/bin/golangci-lint run
        go test ./...
      env:
        GOPATH: /tmp/gopath
